packaging_format = 2

id = "lemmy"
name = "Lemmy"
description.en = "Link aggregator/Reddit clone for the fediverse"
description.fr = "Agrégateur de liens/clone Reddit pour le fedivers"

version = "2023.08.09~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://join-lemmy.org/"
demo = "https://lemmy.ml/"
admindoc = "https://join-lemmy.org/docs/en/"
code = "https://github.com/LemmyNet/lemmy"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64"]
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "500M"
ram.runtime = "50M"

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/jjlin/docker-image-extract/archive/4273b2796da5055e431b4db5efe29a71bba12b45.tar.gz"
        sha256 = "8e582bb186bdb1053051ad6be8829ebb4af418cb4e43005efc9d7749e0269cba"
        autoupdate.upstream = "https://github.com/jjlin/docker-image-extract"
        autoupdate.strategy = "latest_github_commit"

        [resources.sources.lemmy-translations]
        url = "https://github.com/LemmyNet/lemmy-translations/archive/8bb90fa4a30e6dc2ba4449794e99d6b3325bebb5.tar.gz"
        sha256 = "5ac1bed16753d578a931c3a1d71c2b116a22db27ffc9b7282b61b4ac4102760a"
        autoupdate.upstream = "https://github.com/LemmyNet/lemmy-translations/"
        autoupdate.strategy = "latest_github_commit"

    [resources.ports]
    main.default = 8536
    ui.default = 1235

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["pictrs-data"]

    [resources.permissions]
    main.url = "/"
    
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false
    api.protected = true

    inbox.url = "/inbox"
    inbox.allowed = "visitors"
    inbox.auth_header = false
    inbox.show_tile = false
    inbox.protected = true

    [resources.apt]
    packages = "postgresql, espeak, rsync"
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "postgresql"
